### ISSUE TITLE
streamlit_extras\__init__.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by chincherpa** [arnaudmiribel/streamlit-extras#89]
Hi,

I get following exception:
Traceback (most recent call last):
  File "c:/Users/Public/Documents/BankAccount/test_drop.py", line 2, in <module>
    from streamlit_extras.dataframe_explorer import dataframe_explorer
  File "C:\Python38\lib\site-packages\streamlit_extras\dataframe_explorer\__init__.py", line 16, in <module>
    def dataframe_explorer(df: pd.DataFrame) -> pd.DataFrame:
  File "C:\Python38\lib\site-packages\streamlit_extras\__init__.py", line 41, in extra
    submodule = filename.split("/")[-2]
IndexError: list index out of range

My code:
```
from streamlit_extras.dataframe_explorer import dataframe_explorer
```
Yes, 1 line.

Used versions:
Python 3.8.5

streamlit                   1.15.1
streamlit-extras            0.2.2

**Comment by arnaudmiribel** [comment]
Hey @chincherpa, definitely looks like a Windows bug on our side when parsing paths -- Will try to give this a fix quickly! Thanks for filing an issue

**Comment by chincherpa** [comment]
It is fixed.
Thank you
